### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by soldierbupt** [zhedahht/OfferOrientedAlgorithms#1]
您好！看纸质版书籍时发现一处可能的错误。
面试题89房屋偷盗
249页倒数第七行 f(1)=nums[0]应该是f(0)
=nums[0]

**Comment by zhedahht** [comment]
谢谢您发现并告知书中的问题。这的确是一处笔误，已添加到勘误列表里。再次印刷的时候将通知出版社修改。
